/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GiottoBizzarriniRouteImport } from './routes/giotto-bizzarrini'
import { Route as ExpertCertificateRouteImport } from './routes/expert-certificate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoituresIdRouteImport } from './routes/voitures.$id'
import { Route as ChassisSlugRouteImport } from './routes/chassis.$slug'
import { Route as ApiNotifySignupRouteImport } from './routes/api/notify-signup'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GiottoBizzarriniRoute = GiottoBizzarriniRouteImport.update({
  id: '/giotto-bizzarrini',
  path: '/giotto-bizzarrini',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertCertificateRoute = ExpertCertificateRouteImport.update({
  id: '/expert-certificate',
  path: '/expert-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoituresIdRoute = VoituresIdRouteImport.update({
  id: '/voitures/$id',
  path: '/voitures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChassisSlugRoute = ChassisSlugRouteImport.update({
  id: '/chassis/$slug',
  path: '/chassis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifySignupRoute = ApiNotifySignupRouteImport.update({
  id: '/api/notify-signup',
  path: '/api/notify-signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/expert-certificate': typeof ExpertCertificateRoute
  '/giotto-bizzarrini': typeof GiottoBizzarriniRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/api/notify-signup': typeof ApiNotifySignupRoute
  '/chassis/$slug': typeof ChassisSlugRoute
  '/voitures/$id': typeof VoituresIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/expert-certificate': typeof ExpertCertificateRoute
  '/giotto-bizzarrini': typeof GiottoBizzarriniRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/api/notify-signup': typeof ApiNotifySignupRoute
  '/chassis/$slug': typeof ChassisSlugRoute
  '/voitures/$id': typeof VoituresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/expert-certificate': typeof ExpertCertificateRoute
  '/giotto-bizzarrini': typeof GiottoBizzarriniRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/api/notify-signup': typeof ApiNotifySignupRoute
  '/chassis/$slug': typeof ChassisSlugRoute
  '/voitures/$id': typeof VoituresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/contact'
    | '/expert-certificate'
    | '/giotto-bizzarrini'
    | '/reset-password'
    | '/videos'
    | '/api/notify-signup'
    | '/chassis/$slug'
    | '/voitures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/contact'
    | '/expert-certificate'
    | '/giotto-bizzarrini'
    | '/reset-password'
    | '/videos'
    | '/api/notify-signup'
    | '/chassis/$slug'
    | '/voitures/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/contact'
    | '/expert-certificate'
    | '/giotto-bizzarrini'
    | '/reset-password'
    | '/videos'
    | '/api/notify-signup'
    | '/chassis/$slug'
    | '/voitures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  ExpertCertificateRoute: typeof ExpertCertificateRoute
  GiottoBizzarriniRoute: typeof GiottoBizzarriniRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VideosRoute: typeof VideosRoute
  ApiNotifySignupRoute: typeof ApiNotifySignupRoute
  ChassisSlugRoute: typeof ChassisSlugRoute
  VoituresIdRoute: typeof VoituresIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giotto-bizzarrini': {
      id: '/giotto-bizzarrini'
      path: '/giotto-bizzarrini'
      fullPath: '/giotto-bizzarrini'
      preLoaderRoute: typeof GiottoBizzarriniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-certificate': {
      id: '/expert-certificate'
      path: '/expert-certificate'
      fullPath: '/expert-certificate'
      preLoaderRoute: typeof ExpertCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voitures/$id': {
      id: '/voitures/$id'
      path: '/voitures/$id'
      fullPath: '/voitures/$id'
      preLoaderRoute: typeof VoituresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chassis/$slug': {
      id: '/chassis/$slug'
      path: '/chassis/$slug'
      fullPath: '/chassis/$slug'
      preLoaderRoute: typeof ChassisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-signup': {
      id: '/api/notify-signup'
      path: '/api/notify-signup'
      fullPath: '/api/notify-signup'
      preLoaderRoute: typeof ApiNotifySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  ExpertCertificateRoute: ExpertCertificateRoute,
  GiottoBizzarriniRoute: GiottoBizzarriniRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VideosRoute: VideosRoute,
  ApiNotifySignupRoute: ApiNotifySignupRoute,
  ChassisSlugRoute: ChassisSlugRoute,
  VoituresIdRoute: VoituresIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
